version: '3.7'
services:
  database:
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: main
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - '3306'
    volumes:
      - ./database:/docker-entrypoint-initdb.d
  front:
    container_name: front
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 80:3000
    environment:
      - CHOKIDAR_USEPOLLING=true